services:
  mysql:
    image: mysql:8.0
    container_name: fresh-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123      
      MYSQL_DATABASE: fresh                # do not change name of the script db name
      MYSQL_USER: ${DB_USER:-freshuser}          
      MYSQL_PASSWORD: ${DB_PASS:-freshpass}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - ./docs/db/migrations:/docker-entrypoint-initdb.d
      - ./docs/db/seed/dump.sql:/docker-entrypoint-initdb.d/9999_seed.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fresh-api
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      ADDRESS: ${ADDRESS:-8080}
      DB_HOST: mysql                    # name of the service in dockerfile
      DB_PORT: ${DB_PORT:-3306}
      DB_NAME: fresh                    # do not change name of the script db name
      DB_USER: ${DB_USER:-freshuser}
      DB_PASS: ${DB_PASS:-freshpass}
    ports:
      - "${ADDRESS:-8080}:8080"