version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: fresh-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123      
      MYSQL_DATABASE: fresh                # no cambiar, el script la crea con fresh
      MYSQL_USER: ${DB_USER}            
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - ./docs/db/init:/docker-entrypoint-initdb.d
      # - ./docs/db/seed/:/docker-entrypoint-initdb.d/seed
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fresh-api
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      ADDRESS: ${ADDRESS}
      DB_HOST: mysql      
      DB_PORT: ${DB_PORT}
      DB_NAME: fresh      # no cambiar, el script la crea con fresh
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    ports:
      - "8080:8080"